// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface SendLogin {
    email:    string;
    password: string;
}

export interface DataResponseLogin {
    token: string;
}